version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverse-proxy
    image: tinepapa/udagram-reverse-proxy
  backend_user:
    build:
      context: ./udagram-users-api
    image: tinepapa/udagram-users-api
  backend_feed:
    build:
      context: ./udagram-feed-api
    image: tinepapa/udagram-feed-api
  frontend:
    build:
      context: ./udagram-frontend
    image: tinepapa/udagram-frontend
