apiVersion: v1
kind: Secret
metadata:
  name: test-secret # Name of the secret
  namespace: default # Namespace of the secret
data:
  userData: "encoded-cloud-config" # AWS cloud config file (base64 encoded)
  providerAccessKeyId: "QVNJQTZLNzZEQ1dERDNFTzRIQjQ=" # AWS access key id (base64 encoded)
  providerSecretAccessKey: "M0FLbFZadnRPcDRFTjBVRUhFSEZGY0s4aG9uM1FicWQwZUxzM3A2Yg==" # AWS secret access key (base64 encoded)
### Alternative data keys are:
# accessKeyId: "pqrstu67890" # AWS access key id (base64 encoded)
# secretAccessKey: "abcdef123456" # AWS secret access key (base64 encoded)
type: Opaque