apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user-service
  namespace: udagram
  labels:
    app: udagram-api-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-api-user