apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  POSTGRES_USERNAME: udagramtinedev
  POSTGRES_PASSWORD: udagramtine22
  POSTGRES_HOST: udagramtinedev.cgkbkws7etz9.us-east-1.rds.amazonaws.com
  POSTGRES_DB: udagramtinedev
  AWS_BUCKET: s3b985691002246
  AWS_REGION: us-east-1
  AWS_PROFILE: default
  JWT_SECRET: helloworld
  URL: http://localhost:8100
