version: '3'

services:
  reverse-proxy:
    image: tinepapa/udagram-reverse-proxy
    ports:
      - '8080:80'

  feed-api-svc:
    image: tinepapa/udagram-feed-api
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_REGION: ${AWS_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      JWT_SECRET: ${JWT_SECRET}
      URL: ${URL}
    volumes:
      - C:\Users\tine028547\.aws
    ports:
      - '8081:8081'

  users-api-svc:
    image: tinepapa/udagram-users-api
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      URL: ${URL}
    ports:
      - '8082:8082'

  frontend:
    image: tinepapa/udagram-frontend
    ports:
      - '4200:8080'
