apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api
  labels:
    app: feed-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
      - name: feed-api
        image: tinepapa/udagram-feed-api:latest
        env:
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: env-config
              key: aws_bucket
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: env-config
              key: aws_profile
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: env-config
              key: aws_region
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-config
              key: jwt_secret
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: env-config
              key: postgres_db
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: env-config
              key: postgres_host
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-config
              key: postgres_password
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-config
              key: postgres_username
        - name: URL
          valueFrom:
            secretKeyRef:
              name: env-config
              key: url
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
